local path = core.get_modpath("mobs_animal")

dofile(path .. "/bear.lua")
dofile(path .. "/bunny.lua")
dofile(path .. "/chicken.lua")
dofile(path .. "/cow.lua")
dofile(path .. "/dog.lua")
dofile(path .. "/kitten.lua")
dofile(path .. "/pig.lua")
dofile(path .. "/sheep.lua")